import { Shop } from './srp/entitens/shop';
import { Order } from './srp/entitens/order';
import { Message } from './srp/services/msg';
import { Persistence } from './srp/services/persisten';
import { Product } from './srp/entitens/product';
const cart = new Shop();
const msg = new Message();
const persis = new Persistence();
const order = new Order(cart, msg, persis);
cart.addItem(new Product('Pen', 3.49));
cart.addItem(new Product('Book', 12.99));
cart.addItem(new Product('pencil', 1.3));
cart.addItem(new Product('Notebook', 12.99));
console.log(cart.items);
console.log(order.orderStatus);
order.checkout();
console.log(order.orderStatus);
